# Generated by Django 6.0.2 on 2026-04-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itpstudent',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='student_images/'),
        ),
    ]
