# Generated by Django 6.0.2 on 2026-04-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itp_app', '0002_alter_itpstudent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itpstudent',
            name='Image',
            field=models.ImageField(blank=True, default='default.png', upload_to='images/'),
        ),
    ]
